# Generated by Django 4.1.5 on 2023-01-17 06:29

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0004_delete_myaccounts_myaccounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAccounts',
        ),
        migrations.CreateModel(
            name='MyAccount',
            fields=[
            ],
            options={
                'db_table': 'student_info',
                'ordering': ['username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
