# Generated by Django 4.1.5 on 2023-01-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_myaccounts_myaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemb',
            options={'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'ITEM B'},
        ),
        migrations.AlterModelTable(
            name='myaccount',
            table=None,
        ),
    ]
