# Generated by Django 4.1.5 on 2023-01-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_itemb_options_alter_myaccount_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itema',
            options={'get_latest_by': 'created', 'ordering': ['title']},
        ),
    ]
