# Generated by Django 4.1.5 on 2023-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_itema_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('home_group', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itema',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='itemb',
            options={'ordering': ['-created'], 'verbose_name': 'ITEM B', 'verbose_name_plural': 'Item B'},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('home_group__gte', 'home')), name='home_group_gte_18'),
        ),
    ]
